version: '2'
services:
    crowd:
      image: derekbelrose/crowd:2.10.1
      volumes:
        - crowd_logs:/opt/atlassian/crowd/apache-tomcat/logs
        - crowd_home:/var/atlassian/application-data/crowd
      ports:
        - "8095"
      expose:
        - "8095"

    jira:
      depends_on:
        - crowd
      image: derekbelrose/jira:6.3.15
      volumes:
        - "jira_home:/var/atlassian/application-data/jira"
        - "jira_logs:/opt/atlassian/jira/logs"
      ports:
        - "8080"
      links:
        - crowd
      environment:
        - JVM_SUPPORT_RECOMMENDED_ARGS="-Dfile.encoding=utf-8"

    nginx:
      depends_on:
        - jira
        - crowd
      image: nginx
      ports: ["80:80"]
      volumes:
        - "nginx_confd:/etc/nginx/conf.d"
      links:
        - crowd
        - jira
   
volumes:
  crowd_logs:
    external: false
  crowd_home:
    external: false
  jira_logs:
    external: false
  jira_home:
    external: false
  nginx_confd:
    external: false
