version: '2'
services:
    web:
      image: nginx:latest
      links:
	- crowd
   	- jira
    db:
      image: mysql:5.6
      volumes:
        - db:/var/lib/mysql/
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    crowd:
      depends_on:
        - db
      image: derekbelrose/crowd:2.10.1
      volumes:
        - crowd_logs:/opt/atlassian/crowd/apache-tomcat/logs
        - crowd_home:/var/atlassian/application-data/crowd
      ports:
        - "8095"
      expose:
        - "8095"
      links:
        - db

    jira:
      depends_on:
        - crowd
        - db
      image: derekbelrose/jira:6.3.15
      volumes:
        - "jira_home:/var/atlassian/application-data/jira"
        - "jira_logs:/opt/atlassian/jira/logs"
      ports:
        - "8080"
      links:
        - db
        - crowd
      environment:
        - JVM_SUPPORT_RECOMMENDED_ARGS="-Dfile.encoding=utf-8"

volumes:
  db:
    external: false
  crowd_logs:
    external: false
  crowd_home:
    external: false
  jira_logs:
    external: false
  jira_home:
    external: false
