version: '2'
services:
    crowd:
      image: derekbelrose/crowd:2.10.1
      volumes:
        - "/usr/local/atlassian-docker/logs/crowd:/opt/atlassian/crowd/apache-tomcat/logs"
        - "/usr/local/atlassian-docker/crowd/var/atlassian/application-data/crowd:/var/atlassian/application-data/crowd"
        - "/usr/local/atlassian-docker/crowd/opt/atlassian/crowd/apache-tomcat/conf:/opt/atlassian/crowd/apache-tomcat/conf"

      ports:
        - "8095"

    confluence:
      depends_on:
        - crowd
      image: cptactionhank/atlassian-confluence:6.3.4
      volumes:
        - "/usr/local/atlassian-docker/confluence/var/atlassian/confluence:/var/atlassian/confluence"
        - "/usr/local/atlassian-docker/logs/confluence:/opt/atlassian/confluence/logs"
        - "/usr/local/atlassian-docker/confluence/opt/atlassian/confluence/conf:/opt/atlassian/confluence/conf"
      ports:
        - "8090"
      links:
        - crowd
      environment:
        - JVM_SUPPORT_RECOMMENDED_ARGS="-Dfile.encoding=utf-8"

    jira:
      depends_on:
        - crowd
      image: cptactionhank/atlassian-jira:7.6.3
      volumes:
        - "/usr/local/atlassian-docker/jira/var/atlassian/jira:/var/atlassian/jira"
        - "/usr/local/atlassian-docker/logs/jira:/opt/atlassian/jira/logs"
        - "/usr/local/atlassian-docker/jira/opt/atlassian/jira/conf:/opt/atlassian/jira/conf"
      ports:
        - "8080"
      links:
        - crowd
      environment:
        - JVM_SUPPORT_RECOMMENDED_ARGS="-Dfile.encoding=utf-8"

    nginx:
      depends_on:
        - crowd
      image: nginx
      ports: ["80:80", "443:443"]
      volumes:
        - "/usr/local/atlassian-docker/nginx/etc/nginx/conf.d:/etc/nginx/conf.d"
      links:
        - crowd
        - jira
        - confluence
